version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3307"  # ใช้พอร์ต 3306 สำหรับ MySQL

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app  # ให้สามารถแก้ไขโค้ดได้
    environment:
      FLASK_ENV: development  # เพื่อให้ Flask รันในโหมดพัฒนา

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

